import React from 'react';
import parse from 'html-react-parser';
import CustomTitle from './custom-title';

const PostCard = () => {
    const htmlString = `<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus, consequuntur! Eum, sapiente eveniet. Accusamus cum quasi ad aliquam recusandae fuga ullam corrupti, repellendus quibusdam? Totam illum cumque nulla corrupti cum! Magni, optio. Illum quae excepturi dicta pariatur odit dolores illo culpa quis officiis quisquam dignissimos ipsa, quo natus dolorem vel repellendus! Est necessitatibus optio saepe fuga, assumenda vitae fugit et possimus ipsam! Dicta alias dignissimos vero, ullam autem fuga eius asperiores, ipsam debitis sapiente distinctio expedita tenetur impedit assumenda ipsa at velit quibusdam cumque sequi! Sint enim, facilis iusto veritatis eum, itaque dicta adipisci voluptatibus porro pariatur deserunt nihil? Sit?</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident harum, sit molestias explicabo saepe fugiat est ipsa nulla, accusamus omnis autem, numquam non illo! Perspiciatis id ex minus assumenda officiis aperiam! Iste excepturi fuga adipisci unde nostrum repudiandae corrupti velit, sit earum mollitia! Aliquid vero provident illum, consequuntur voluptate recusandae consectetur. Iste veniam quos laudantium odit quo nihil doloribus maxime molestiae, quis expedita et mollitia nisi deserunt non atque iure rem repellat nobis! Modi cumque maxime cupiditate nulla excepturi qui.</p>
    <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Assumenda placeat odio exercitationem cum. Dicta commodi accusamus distinctio sed qui necessitatibus nobis blanditiis, consectetur harum laboriosam possimus rem eaque dolorem maiores tempore atque nihil accusantium cum nemo facere quis velit enim mollitia provident! Dignissimos, inventore, consectetur amet eligendi reiciendis sint quo cupiditate soluta tenetur deserunt error, distinctio dolores neque mollitia nihil hic quaerat quod eveniet odio facere et. Eius sequi commodi incidunt reiciendis, officiis ipsa. Minima natus non beatae quae magni facilis asperiores, voluptas recusandae dignissimos, a doloremque? Sit quibusdam et veritatis fuga. Nihil dolorum maxime nemo temporibus. Officia, dolorum ratione maiores commodi adipisci aliquam, a cumque qui, sapiente quasi quidem esse? Iusto eligendi magni enim consectetur perspiciatis fugit illo officiis dolor saepe corporis. Maiores vero autem ad sit officia optio mollitia ullam tempora dolores, quam illo distinctio ex earum, suscipit soluta rerum labore libero rem cum architecto tempore perspiciatis. Explicabo, dolore, animi autem doloribus cupiditate maxime eligendi culpa fugit delectus labore sed commodi cumque harum dolor enim qui hic inventore expedita assumenda odit nobis. Saepe non repellat impedit officia unde quo cum, qui hic eligendi dignissimos vero natus eum itaque, nihil ea ex magni cupiditate veritatis dolorum alias nam provident! Quas sint quaerat fugit? Magni iusto minima quos recusandae hic qui architecto, excepturi pariatur reprehenderit soluta ipsa voluptatem quidem quam, alias maiores similique quisquam beatae? Officia exercitationem placeat, sequi nemo aperiam vero inventore ea necessitatibus quia, corporis iusto sapiente quod beatae mollitia, nulla quibusdam laborum aliquam vitae dolorem sunt est tempore! Quo atque tempora natus ad, voluptas cum debitis repellat amet, iusto maxime voluptatum necessitatibus odio adipisci maiores nisi? Porro aut tempore commodi eligendi, perferendis perspiciatis temporibus nisi mollitia ullam quos omnis earum deserunt hic magnam! Consequatur corrupti obcaecati tempore, assumenda magnam vero quidem. Sit quidem in natus facilis et labore officia, vitae eum ad nemo alias sed enim mollitia. Eaque repudiandae odio vero quis ullam corporis mollitia nam possimus? Dolore accusantium quae laudantium deserunt, sequi ullam unde neque ad praesentium consequatur, rerum natus, optio maxime temporibus nemo earum asperiores impedit voluptatum? Animi doloribus, natus distinctio neque repudiandae ab ut sit culpa rem officia hic dolore recusandae assumenda, quis, voluptatibus nostrum nobis harum iusto tempore placeat. Saepe, vero numquam earum mollitia et sunt perferendis totam, quam accusamus maiores exercitationem nisi in sequi porro quidem recusandae, laboriosam natus error quod quas. Aliquam quisquam impedit amet vitae asperiores temporibus minus iste explicabo?</p>`;
    return (
        <div
            className={`bg-neutral-100 border-b-4 border-b-primary p-4 md:pt-10 md:pb-16 md:px-20 my-8`}
        >
            <CustomTitle>Saepe obcaecati praesentium amet molestiae</CustomTitle>
            <Content content={htmlString} />
        </div>
    );
};

export default PostCard;

function Content({ content }: { content: string }) {
    return <>{parse(content)}</>;
}
